---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
- name: Redhat !
  include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'
- name: Debian !
  include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'
- name: AMazon Linux !
  include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'Amazon'
- name: Ubuntu !
  include_tasks: setup-Ubuntu.yml
  when: ansible_os_family == 'Ubuntu'
- name: Force default nginx.conf file
  template:
    src: "nginx-config.j2"
    dest: "/etc/nginx/nginx.conf"
  notify: Restart nginx
