---
- name: install nginx in ubuntu
  apt:
    name: "{{ nginx_package }}"
    state: present
    update_cache: yes
- name: start nginx ubuntu
  service:
    name: "{{ nginx_service }}"
    state: started
