---
- name: Update apt cache.
  apt:
   update_cache: yes
   cache_valid_time: 86400
  changed_when: false
- name: Create directory for stream conf files
  file:
   path: "{{ nginx_path }}"
   state: directory
- name: Ensure nginx is installed.
  apt:
   name: "{{ nginx_package }}"
   state: present
